[tool.black]
line-length = 100
target-version = ["py312"]
exclude = [
  "/migrations/",
]

[tool.isort]
profile = "black"
line_length = 100
skip = ["migrations"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = ["migrations", ".venv"]
